name: Develop

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.2.0
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'pnpm'
      - name: Install npm dependencies
        run: pnpm install
      - name: Run build task
        run: pnpm build
      - name: zip bundle file
        run: zip -r ctx.zip extension/
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: ctx
          path: ctx.zip